services:
  database:
    image: timescale/timescaledb:2.15.1-pg15
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.server
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_schema:/docker-entrypoint-initdb.d
    networks:
      - trading_net

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - trading_net

  backend:
    build:
      context: .
      dockerfile: ./DB_backend/Dockerfile.server
    container_name: backend
    depends_on:
      - database
      - redis
    restart: always
    env_file:
      - .env.server
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./DB_backend:/app
    networks:
      - trading_net

  worker:
    build:
      context: .
      dockerfile: ./DB_backend/Dockerfile.server
    container_name: worker
    command: celery -A celery_task.celery_app worker --loglevel=info --concurrency=4
    depends_on:
      - database
      - redis
      - backend
    restart: always
    env_file:
      - .env.server
    working_dir: /app
    volumes:
      - ./DB_backend:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - trading_net

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.server
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_BACKTESTING_BACKEND_URL: ${VITE_BACKTESTING_BACKEND_URL}
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    env_file:
      - .env.server
    networks:
      - trading_net
    
  backtesting_backend:
    build:
      context: .
      dockerfile: ./backtesting_backend/Dockerfile.server
    container_name: backtesting_backend
    depends_on:
      - database
      - redis
    restart: always
    env_file:
      - .env.server
    ports:
      - "8002:8002"
    working_dir: /app
    volumes:
      - ./backtesting_backend:/app
    networks:
      - trading_net


networks:
  trading_net:
    driver: bridge

volumes:
  db_data:
